### ISSUE TITLE
RGB channel or Y channel PSNR and SSIM?

### ISSUE THREAD

**Issue by Jian-danai** [jnjaby/DISCNet#11]
Hi, I was wondering which one did you use in the evaluation?

(1) **RGB channel or Y channel** PSNR and SSIM?

It seems you didn't mention it in your paper.

Also (2) I want to know **whether you post-processed the images before calculating the PSNR and SSIM**?

(3) Did you post-processed the images before putting them in your supplementary material - qualitative results?

Thanks.

**Comment by jnjaby** [comment]
1. All evaluations are done on RGB images.
2. We only apply post-processing to real images for better visualization, so no reference-based metric can be calculated since the ground-truth images are not accessible. 
3. Yes.

**Comment by Jian-danai** [comment]
> 1. All evaluations are done on RGB images.
> 2. We only apply post-processing to real images for better visualization, so no reference-based metric can be calculated since the ground-truth images are not accessible.
> 3. Yes.

1. Do you mean you **set test_Y_channel to false** in _/options/test/DISCNet_test_real_data.yml and /options/test/DISCNet_test_synthetic_data.yml_ when calculating PSNR and SSIM?
2. Do you mean you only apply post-processing after testing **real** images?  Do you apply post-processing after testing **synthetic** images?
3. I just want to make sure again, which one of the following do you use when calculating the PSNR? (You may choose 2 of them)
A. RGB_channel_PSNR (Post-processing (DISNetmodel (input_synthetic_data)), Groundtruth)
B. RGB_channel_PSNR (DISNetmodel (input_synthetic_data), Groundtruth)
C. RGB_channel_PSNR (Post-processing (DISNetmodel (input_real_data)), Groundtruth)
D. RGB_channel_PSNR (DISNetmodel (input_real_data), Groundtruth)

4. How did you get the ccm (color correction matrix), can I do post-processing on synthetic results because it seems the results from pretrained_model(synthetic_input_data) have different colors and contrast from the GT as follows:
Output:
![kloppenheim_02_8k_fov90_theta60_phi0_c](https://user-images.githubusercontent.com/42494274/134979240-bd4c43d5-b0d1-467e-930d-a2ea18121a7e.png)
GT:
![kloppenheim_02_8k_fov90_theta60_phi0_c](https://user-images.githubusercontent.com/42494274/134979597-0c209937-32f1-4442-89b8-daf898baf835.png)
I am not sure whether there is any problem when transferring GT(hdr) to GT(ldr). Could you provide the code to visualize the GT(hdr) or to transfer GT(hdr) to GT(ldr)?

Sorry for the inconvenience!!

**Comment by jnjaby** [comment]
Hi, for `DISCNet_test_synthetic_data.yml`, you can set **test_Y_channel** to _false_ as default. In fact, evaluation on Y channel is an additional option. For `DISCNet_test_real_data.yml`, once again, we have to emphasize there is no metric to be calculated since we have **NO** GT images of the real data.

Please be careful that post-processing is just a simulation of the ISP of the mobile phone. Therefore it is applied on _real_ images (captured by ZTE phone) for better visualization (_e.g._, color, contrast). It won't affect the performance of diffraction artifacts removal.

In a word, we calculate PSNR on _synthetic data_, and post-process the _real data_. To your question, **option B** is correct.

Seems you didn't apply tone mapping on the GT synthetic images before visualization. Note that we save the output images in the tone-mapped domain. If you'd like to compare them with GT images, please refer to [tone mapping](https://github.com/jnjaby/DISCNet/blob/63b1859519091f8790afcc47e8c726cbefdcd0fe/basicsr/data/paired_img-psf_npy_dataset.py#L68).

**Comment by Jian-danai** [comment]
> Hi, for `DISCNet_test_synthetic_data.yml`, you can set **test_Y_channel** to _false_ as default. In fact, evaluation on Y channel is an additional option. For `DISCNet_test_real_data.yml`, once again, we have to emphasize there is no metric to be calculated since we have **NO** GT images of the real data.
> 
> Please be careful that post-processing is just a simulation of the ISP of the mobile phone. Therefore it is applied on _real_ images (captured by ZTE phone) for better visualization (_e.g._, color, contrast). It won't affect the performance of diffraction artifacts removal.
> 
> In a word, we calculate PSNR on _synthetic data_, and post-process the _real data_. To your question, **option B** is correct.
> 
> Seems you didn't apply tone mapping on the GT synthetic images before visualization. Note that we save the output images in the tone-mapped domain. If you'd like to compare them with GT images, please refer to [tone mapping](https://github.com/jnjaby/DISCNet/blob/63b1859519091f8790afcc47e8c726cbefdcd0fe/basicsr/data/paired_img-psf_npy_dataset.py#L68).

Thanks for your kind help!!
